### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by hosseinkhojany** [hossinasaadi/V2Box-Linux#2]
https://github.com/hossinasaadi/V2Box-Linux/blob/master/Tunnel/tunnel.sh
how to make this script compatible for macos

**Comment by hossinasaadi** [comment]
I only implemented linux routing configuration in tunnel.sh and as I mentioned in readme file this repo use tun2socks lib, that you can see macOS example here:
https://github.com/xjasonlyu/tun2socks/wiki/Examples#macos

feel free to contribute if you implement macOS

**Comment by hosseinkhojany** [comment]
it not worked bro 😭
