### ISSUE TITLE
compatibility issue for importing android json config file to ios v2box json config file

### ISSUE THREAD

**Issue by aminhashemi1994** [hossinasaadi/V2Box-Linux#4]
i get wrong json in ios but the exact config imports and works on androind v2box.

how can i fix this problem? i cannot share my configs here but im am multiple times checked that the json is correct and i diff check it before importing in ios but no chance of importing it.

how can i fix this problem?

**Comment by hossinasaadi** [comment]
this repo is sample for linux, there is no android version :)
